workflows:
  android_release:
    name: Android Release Build
    max_build_duration: 60
    environment:
      flutter: stable
    scripts:
      - name: Get Flutter packages
        script: flutter pub get
      - name: Build Android APK (release)
        script: flutter build apk --release
      - name: Build Android App Bundle (release)
        script: flutter build appbundle --release
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
      - build/app/outputs/bundle/release/*.aab
