// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASxqd6LlP8Pp3h6nSsYdpCwZc9UPJgDck',
    appId: '1:130435474815:web:1c6693ca63e23d941ce64a',
    messagingSenderId: '130435474815',
    projectId: 'mybudjet-e75a2',
    authDomain: 'mybudjet-e75a2.firebaseapp.com',
    storageBucket: 'mybudjet-e75a2.firebasestorage.app',
    measurementId: 'G-EC57MXLW7F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhe1uLbM3NJ6ikDGFOYnLtA_nJU5Y_Pwo',
    appId: '1:130435474815:android:df8a93bbab94ce5a1ce64a',
    messagingSenderId: '130435474815',
    projectId: 'mybudjet-e75a2',
    storageBucket: 'mybudjet-e75a2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJ92S5QAtfK8GfPVsgfEJf428aph9Tu34',
    appId: '1:130435474815:ios:e49a9985be2eb7f61ce64a',
    messagingSenderId: '130435474815',
    projectId: 'mybudjet-e75a2',
    storageBucket: 'mybudjet-e75a2.firebasestorage.app',
    iosBundleId: 'com.example.myBudjet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJ92S5QAtfK8GfPVsgfEJf428aph9Tu34',
    appId: '1:130435474815:ios:e49a9985be2eb7f61ce64a',
    messagingSenderId: '130435474815',
    projectId: 'mybudjet-e75a2',
    storageBucket: 'mybudjet-e75a2.firebasestorage.app',
    iosBundleId: 'com.example.myBudjet',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyASxqd6LlP8Pp3h6nSsYdpCwZc9UPJgDck',
    appId: '1:130435474815:web:afc449e3b2730aa41ce64a',
    messagingSenderId: '130435474815',
    projectId: 'mybudjet-e75a2',
    authDomain: 'mybudjet-e75a2.firebaseapp.com',
    storageBucket: 'mybudjet-e75a2.firebasestorage.app',
    measurementId: 'G-PJWFMBF3RX',
  );
}
