platform :ios, '15.0'

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  # במקום לקרוא לקובץ חיצוני, אנחנו פשוט אומרים לו להשתמש ב-Pods
  pod 'Firebase/Firestore'
  pod 'Firebase/Core'
end